const projectsData = [
  {
    "id": "airport-retail",
    "title": "Airport Retail Campaigns",
    "client": "Rogers, Fido & Chatr",
    "category": "retail",
    "categoryLabel": "Retail & OOH",
    "scope": "Airport kiosk displays, employee promotions, flyer assets, & hardware financing campaigns.",
    "description": "This project delivers comprehensive retail marketing systems for major Canadian telecom brands. It establishes key visual touchpoints inside airport lounges and arrivals halls across Halifax, Winnipeg, and Toronto Pearson airports. Layouts advertise phone plans, Samsung watch bundles, and hardware financing options using clean, readable grids tailored to airport traveler traffic.",
    "image": "portfolio/airport-retail/both_brands_clean.png",
    "fileLink": "portfolio/airport-retail/both_brands_clean.png",
    "fileType": "image",
    "fileLabel": "View Asset",
    "imagesList": [
      "portfolio/airport-retail/both_brands_clean.png",
      "portfolio/airport-retail/image_2.jpg",
      "portfolio/airport-retail/image_3.webp",
      "portfolio/airport-retail/image_4.jpg",
      "portfolio/airport-retail/image_5.jpg",
      "portfolio/airport-retail/image_6.jpg",
      "portfolio/airport-retail/image_7.jpg",
      "portfolio/airport-retail/image_9.jpg",
      "portfolio/airport-retail/image_11.jpg",
      "portfolio/airport-retail/image_13.jpg",
      "portfolio/airport-retail/image_15.png",
      "portfolio/airport-retail/image_16.jpg",
      "portfolio/airport-retail/image_17.jpg",
      "portfolio/airport-retail/image_18.jpg",
      "portfolio/airport-retail/image_19.jpg",
      "portfolio/airport-retail/image_20.jpg",
      "portfolio/airport-retail/image_21.jpg",
      "portfolio/airport-retail/image_22.jpg",
      "portfolio/airport-retail/image_23.jpg",
      "portfolio/airport-retail/image_24.jpg",
      "portfolio/airport-retail/image_25.jpg",
      "portfolio/airport-retail/image_26.jpg",
      "portfolio/airport-retail/image_27.png",
      "portfolio/airport-retail/image_28.jpg",
      "portfolio/airport-retail/image_29.jpg",
      "portfolio/airport-retail/image_30.jpg",
      "portfolio/airport-retail/image_31.jpg",
      "portfolio/airport-retail/image_32.jpg",
      "portfolio/airport-retail/image_33.jpg",
      "portfolio/airport-retail/image_34.png",
      "portfolio/airport-retail/image_35.jpg",
      "portfolio/airport-retail/image_36.jpg",
      "portfolio/airport-retail/image_37.jpg",
      "portfolio/airport-retail/image_38.jpg",
      "portfolio/airport-retail/image_39.jpg",
      "portfolio/airport-retail/image_40.jpg",
      "portfolio/airport-retail/image_41.jpg",
      "portfolio/airport-retail/image_42.jpg",
      "portfolio/airport-retail/image_43.jpg",
      "portfolio/airport-retail/image_44.jpg",
      "portfolio/airport-retail/image_46.jpg",
      "portfolio/airport-retail/image_47.jpg",
      "portfolio/airport-retail/image_48.jpg",
      "portfolio/airport-retail/image_49.jpg",
      "portfolio/airport-retail/image_50.jpg",
      "portfolio/airport-retail/image_51.jpg",
      "portfolio/airport-retail/image_52.jpg",
      "portfolio/airport-retail/image_53.jpg",
      "portfolio/airport-retail/image_54.jpg",
      "portfolio/airport-retail/image_55.jpg",
      "portfolio/airport-retail/image_56.jpg",
      "portfolio/airport-retail/image_58.jpg",
      "portfolio/airport-retail/image_59.jpg",
      "portfolio/airport-retail/image_60.png",
      "portfolio/airport-retail/image_61.jpg"
    ],
    "featuredImages": [
      "portfolio/airport-retail/both_brands_clean.png",
      "portfolio/airport-retail/image_2.jpg",
      "portfolio/airport-retail/image_3.webp",
      "portfolio/airport-retail/image_4.jpg",
      "portfolio/airport-retail/image_5.jpg",
      "portfolio/airport-retail/image_6.jpg",
      "portfolio/airport-retail/image_7.jpg",
      "portfolio/airport-retail/image_9.jpg",
      "portfolio/airport-retail/image_11.jpg"
    ],
    "archiveImages": [
      "portfolio/airport-retail/image_13.jpg",
      "portfolio/airport-retail/image_15.png",
      "portfolio/airport-retail/image_16.jpg",
      "portfolio/airport-retail/image_17.jpg",
      "portfolio/airport-retail/image_18.jpg",
      "portfolio/airport-retail/image_19.jpg",
      "portfolio/airport-retail/image_20.jpg",
      "portfolio/airport-retail/image_21.jpg",
      "portfolio/airport-retail/image_22.jpg",
      "portfolio/airport-retail/image_23.jpg",
      "portfolio/airport-retail/image_24.jpg",
      "portfolio/airport-retail/image_25.jpg",
      "portfolio/airport-retail/image_26.jpg",
      "portfolio/airport-retail/image_27.png",
      "portfolio/airport-retail/image_28.jpg",
      "portfolio/airport-retail/image_29.jpg",
      "portfolio/airport-retail/image_30.jpg",
      "portfolio/airport-retail/image_31.jpg",
      "portfolio/airport-retail/image_32.jpg",
      "portfolio/airport-retail/image_33.jpg",
      "portfolio/airport-retail/image_34.png",
      "portfolio/airport-retail/image_35.jpg",
      "portfolio/airport-retail/image_36.jpg",
      "portfolio/airport-retail/image_37.jpg",
      "portfolio/airport-retail/image_38.jpg",
      "portfolio/airport-retail/image_39.jpg",
      "portfolio/airport-retail/image_40.jpg",
      "portfolio/airport-retail/image_41.jpg",
      "portfolio/airport-retail/image_42.jpg",
      "portfolio/airport-retail/image_43.jpg",
      "portfolio/airport-retail/image_44.jpg",
      "portfolio/airport-retail/image_46.jpg",
      "portfolio/airport-retail/image_47.jpg",
      "portfolio/airport-retail/image_48.jpg",
      "portfolio/airport-retail/image_49.jpg",
      "portfolio/airport-retail/image_50.jpg",
      "portfolio/airport-retail/image_51.jpg",
      "portfolio/airport-retail/image_52.jpg",
      "portfolio/airport-retail/image_53.jpg",
      "portfolio/airport-retail/image_54.jpg",
      "portfolio/airport-retail/image_55.jpg",
      "portfolio/airport-retail/image_56.jpg",
      "portfolio/airport-retail/image_58.jpg",
      "portfolio/airport-retail/image_59.jpg",
      "portfolio/airport-retail/image_60.png",
      "portfolio/airport-retail/image_61.jpg"
    ]
  },
  {
    "id": "ooh-experiential",
    "title": "OOH & Experiential Displays",
    "client": "Rogers, Fido & Chatr",
    "category": "retail",
    "categoryLabel": "Retail & OOH",
    "scope": "Out-of-Home digital signage, mall billboards, interactive kiosks, & performance tracking.",
    "description": "A diverse array of out-of-home advertising campaigns, specializing in digital menu boards (DineSpace) and interactive standees (like the Soccer Challenge campaign at Georgian Mall). This campaign system incorporates official Proof-of-Performance reports validating layout execution across high-density urban areas.",
    "image": "portfolio/ooh-experiential/iphone_17_clean.png",
    "fileLink": "portfolio/ooh-experiential/iphone_17_clean.png",
    "fileType": "image",
    "fileLabel": "View Asset",
    "imagesList": [
      "portfolio/ooh-experiential/iphone_17_clean.png",
      "portfolio/ooh-experiential/image_2.jpeg",
      "portfolio/ooh-experiential/image_3.jpeg",
      "portfolio/ooh-experiential/image_4.jpg",
      "portfolio/ooh-experiential/image_5.jpeg",
      "portfolio/ooh-experiential/image_6.jpeg",
      "portfolio/ooh-experiential/image_7.jpeg",
      "portfolio/ooh-experiential/image_8.jpeg",
      "portfolio/ooh-experiential/image_9.jpeg",
      "portfolio/ooh-experiential/image_10.jpeg",
      "portfolio/ooh-experiential/image_11.jpg",
      "portfolio/ooh-experiential/image_12.jpg",
      "portfolio/ooh-experiential/image_13.jpg",
      "portfolio/ooh-experiential/image_14.jpg",
      "portfolio/ooh-experiential/image_15.jpeg",
      "portfolio/ooh-experiential/image_16.jpeg",
      "portfolio/ooh-experiential/image_17.jpeg",
      "portfolio/ooh-experiential/image_18.jpg"
    ],
    "featuredImages": [
      "portfolio/ooh-experiential/iphone_17_clean.png",
      "portfolio/ooh-experiential/image_2.jpeg",
      "portfolio/ooh-experiential/image_3.jpeg",
      "portfolio/ooh-experiential/image_4.jpg",
      "portfolio/ooh-experiential/image_5.jpeg",
      "portfolio/ooh-experiential/image_6.jpeg"
    ],
    "archiveImages": [
      "portfolio/ooh-experiential/image_7.jpeg",
      "portfolio/ooh-experiential/image_8.jpeg",
      "portfolio/ooh-experiential/image_9.jpeg",
      "portfolio/ooh-experiential/image_10.jpeg",
      "portfolio/ooh-experiential/image_11.jpg",
      "portfolio/ooh-experiential/image_12.jpg",
      "portfolio/ooh-experiential/image_13.jpg",
      "portfolio/ooh-experiential/image_14.jpg",
      "portfolio/ooh-experiential/image_15.jpeg",
      "portfolio/ooh-experiential/image_16.jpeg",
      "portfolio/ooh-experiential/image_17.jpeg",
      "portfolio/ooh-experiential/image_18.jpg"
    ]
  },
  {
    "id": "airtel-black",
    "title": "Airtel Black Launch",
    "client": "Bharti Airtel (Airtel Black)",
    "category": "retail",
    "categoryLabel": "Retail & OOH",
    "scope": "Launch marketing, emailer (EDM) design, animation, & premium product presentation.",
    "description": "A digital launch marketing strategy for Bharti Airtel's premium bundled subscription plan, Airtel Black. Design files include high-end, responsive email layouts (EDMs) and motion GIFs targeted at presenting custom fiber, DTH, and mobile bundle services as a unified, luxury consumer solution.",
    "image": "portfolio/airtel-black/image_1.jpg",
    "fileLink": "portfolio/airtel-black/image_1.jpg",
    "fileType": "image",
    "fileLabel": "View Asset",
    "imagesList": [
      "portfolio/airtel-black/image_1.jpg",
      "portfolio/airtel-black/image_2.jpg",
      "portfolio/airtel-black/image_3.jpg",
      "portfolio/airtel-black/image_4.jpeg",
      "portfolio/airtel-black/image_5.jpg",
      "portfolio/airtel-black/image_6.gif"
    ],
    "featuredImages": [
      "portfolio/airtel-black/image_1.jpg",
      "portfolio/airtel-black/image_2.jpg",
      "portfolio/airtel-black/image_3.jpg",
      "portfolio/airtel-black/image_4.jpeg",
      "portfolio/airtel-black/image_5.jpg",
      "portfolio/airtel-black/image_6.gif"
    ],
    "archiveImages": []
  },
  {
    "id": "dailyhunt",
    "title": "Dailyhunt Identity Reimagined",
    "client": "Dailyhunt (News Aggregator App)",
    "category": "branding",
    "categoryLabel": "Brand Identity",
    "scope": "Logo design construct, brand guidelines, color theory, & brand books.",
    "description": "A complete reimagining of the visual identity for Dailyhunt, India's premier news aggregator. The branding strategy details a spiral construct merged into the letter 'd', conveying the ever-evolving nature of modern journalism, instant information flow, and growth.",
    "image": "portfolio/dailyhunt/dailyhunt_slide_1.png",
    "fileLink": "portfolio/dailyhunt/dailyhunt_slide_1.png",
    "fileType": "image",
    "fileLabel": "View Asset",
    "imagesList": [
      "portfolio/dailyhunt/dailyhunt_slide_1.png",
      "portfolio/dailyhunt/dailyhunt_slide_2.png",
      "portfolio/dailyhunt/dailyhunt_slide_3.png",
      "portfolio/dailyhunt/dailyhunt_slide_4.png",
      "portfolio/dailyhunt/dailyhunt_slide_5.png",
      "portfolio/dailyhunt/dailyhunt_slide_6.png",
      "portfolio/dailyhunt/dailyhunt_slide_7.png",
      "portfolio/dailyhunt/dailyhunt_slide_8.png",
      "portfolio/dailyhunt/dailyhunt_slide_9.png",
      "portfolio/dailyhunt/dailyhunt_slide_10.png",
      "portfolio/dailyhunt/dailyhunt_slide_11.png",
      "portfolio/dailyhunt/dailyhunt_slide_12.png",
      "portfolio/dailyhunt/dailyhunt_slide_13.png",
      "portfolio/dailyhunt/dailyhunt_slide_14.png",
      "portfolio/dailyhunt/dailyhunt_slide_15.png",
      "portfolio/dailyhunt/dailyhunt_slide_16.png",
      "portfolio/dailyhunt/dailyhunt_slide_17.png",
      "portfolio/dailyhunt/dailyhunt_slide_18.png",
      "portfolio/dailyhunt/dailyhunt_slide_19.png",
      "portfolio/dailyhunt/dailyhunt_slide_20.png",
      "portfolio/dailyhunt/dailyhunt_slide_21.png",
      "portfolio/dailyhunt/dailyhunt_slide_22.png",
      "portfolio/dailyhunt/dailyhunt_slide_23.png",
      "portfolio/dailyhunt/dailyhunt_slide_24.png",
      "portfolio/dailyhunt/dailyhunt_slide_25.png",
      "portfolio/dailyhunt/dailyhunt_slide_26.png",
      "portfolio/dailyhunt/dailyhunt_slide_27.png",
      "portfolio/dailyhunt/dailyhunt_slide_28.png",
      "portfolio/dailyhunt/dailyhunt_slide_29.png",
      "portfolio/dailyhunt/dailyhunt_slide_30.png",
      "portfolio/dailyhunt/dailyhunt_slide_31.png",
      "portfolio/dailyhunt/dailyhunt_slide_32.png",
      "portfolio/dailyhunt/dailyhunt_slide_33.png",
      "portfolio/dailyhunt/dailyhunt_slide_34.png"
    ],
    "featuredImages": [
      "portfolio/dailyhunt/dailyhunt_slide_1.png",
      "portfolio/dailyhunt/dailyhunt_slide_2.png",
      "portfolio/dailyhunt/dailyhunt_slide_3.png",
      "portfolio/dailyhunt/dailyhunt_slide_4.png",
      "portfolio/dailyhunt/dailyhunt_slide_5.png",
      "portfolio/dailyhunt/dailyhunt_slide_6.png",
      "portfolio/dailyhunt/dailyhunt_slide_7.png",
      "portfolio/dailyhunt/dailyhunt_slide_8.png",
      "portfolio/dailyhunt/dailyhunt_slide_9.png",
      "portfolio/dailyhunt/dailyhunt_slide_10.png"
    ],
    "archiveImages": [
      "portfolio/dailyhunt/dailyhunt_slide_11.png",
      "portfolio/dailyhunt/dailyhunt_slide_12.png",
      "portfolio/dailyhunt/dailyhunt_slide_13.png",
      "portfolio/dailyhunt/dailyhunt_slide_14.png",
      "portfolio/dailyhunt/dailyhunt_slide_15.png",
      "portfolio/dailyhunt/dailyhunt_slide_16.png",
      "portfolio/dailyhunt/dailyhunt_slide_17.png",
      "portfolio/dailyhunt/dailyhunt_slide_18.png",
      "portfolio/dailyhunt/dailyhunt_slide_19.png",
      "portfolio/dailyhunt/dailyhunt_slide_20.png",
      "portfolio/dailyhunt/dailyhunt_slide_21.png",
      "portfolio/dailyhunt/dailyhunt_slide_22.png",
      "portfolio/dailyhunt/dailyhunt_slide_23.png",
      "portfolio/dailyhunt/dailyhunt_slide_24.png",
      "portfolio/dailyhunt/dailyhunt_slide_25.png",
      "portfolio/dailyhunt/dailyhunt_slide_26.png",
      "portfolio/dailyhunt/dailyhunt_slide_27.png",
      "portfolio/dailyhunt/dailyhunt_slide_28.png",
      "portfolio/dailyhunt/dailyhunt_slide_29.png",
      "portfolio/dailyhunt/dailyhunt_slide_30.png",
      "portfolio/dailyhunt/dailyhunt_slide_31.png",
      "portfolio/dailyhunt/dailyhunt_slide_32.png",
      "portfolio/dailyhunt/dailyhunt_slide_33.png",
      "portfolio/dailyhunt/dailyhunt_slide_34.png"
    ]
  },
  {
    "id": "houm",
    "title": "Houm Brand Book & Identity",
    "client": "Houm (houm.me)",
    "category": "branding",
    "categoryLabel": "Brand Identity",
    "scope": "Brand book creation, security concepts, galaxy-themed color palettes, & app design.",
    "description": "Branding project for Houm, a startup providing private internet spaces. The logo construct combines a cozy house silhouette (comfort) with a unique thumbprint (private security), rendered with planetary typography alignments and deep cosmic background textures.",
    "image": "portfolio/houm/houm_slide_1.png",
    "fileLink": "portfolio/houm/houm_slide_1.png",
    "fileType": "image",
    "fileLabel": "View Asset",
    "imagesList": [
      "portfolio/houm/houm_slide_1.png",
      "portfolio/houm/houm_slide_2.png",
      "portfolio/houm/houm_slide_3.png",
      "portfolio/houm/houm_slide_4.png",
      "portfolio/houm/houm_slide_5.png",
      "portfolio/houm/houm_slide_6.png",
      "portfolio/houm/houm_slide_7.png",
      "portfolio/houm/houm_slide_8.png",
      "portfolio/houm/houm_slide_9.png",
      "portfolio/houm/houm_slide_10.png",
      "portfolio/houm/houm_slide_11.png",
      "portfolio/houm/houm_slide_12.png",
      "portfolio/houm/houm_slide_13.png",
      "portfolio/houm/houm_slide_14.png",
      "portfolio/houm/houm_slide_15.png",
      "portfolio/houm/houm_slide_16.png",
      "portfolio/houm/houm_slide_17.png",
      "portfolio/houm/houm_slide_18.png",
      "portfolio/houm/houm_slide_19.png",
      "portfolio/houm/houm_slide_20.png",
      "portfolio/houm/houm_slide_21.png",
      "portfolio/houm/houm_slide_22.png",
      "portfolio/houm/houm_slide_23.png",
      "portfolio/houm/houm_slide_24.png",
      "portfolio/houm/houm_slide_25.png",
      "portfolio/houm/houm_slide_26.png",
      "portfolio/houm/houm_slide_27.png",
      "portfolio/houm/houm_slide_28.png",
      "portfolio/houm/houm_slide_29.png",
      "portfolio/houm/houm_slide_30.png",
      "portfolio/houm/houm_slide_31.png",
      "portfolio/houm/houm_slide_32.png",
      "portfolio/houm/houm_slide_33.png",
      "portfolio/houm/houm_slide_34.png",
      "portfolio/houm/houm_slide_35.png",
      "portfolio/houm/houm_slide_36.png",
      "portfolio/houm/houm_slide_37.png",
      "portfolio/houm/houm_slide_38.png",
      "portfolio/houm/houm_slide_39.png",
      "portfolio/houm/houm_slide_40.png",
      "portfolio/houm/houm_slide_41.png",
      "portfolio/houm/houm_slide_42.png",
      "portfolio/houm/houm_slide_44.png",
      "portfolio/houm/houm_slide_45.png",
      "portfolio/houm/houm_slide_46.png",
      "portfolio/houm/houm_slide_47.png"
    ],
    "featuredImages": [
      "portfolio/houm/houm_slide_1.png",
      "portfolio/houm/houm_slide_2.png",
      "portfolio/houm/houm_slide_3.png",
      "portfolio/houm/houm_slide_4.png",
      "portfolio/houm/houm_slide_5.png",
      "portfolio/houm/houm_slide_6.png",
      "portfolio/houm/houm_slide_7.png",
      "portfolio/houm/houm_slide_8.png",
      "portfolio/houm/houm_slide_9.png",
      "portfolio/houm/houm_slide_10.png",
      "portfolio/houm/houm_slide_11.png",
      "portfolio/houm/houm_slide_12.png"
    ],
    "archiveImages": [
      "portfolio/houm/houm_slide_13.png",
      "portfolio/houm/houm_slide_14.png",
      "portfolio/houm/houm_slide_15.png",
      "portfolio/houm/houm_slide_16.png",
      "portfolio/houm/houm_slide_17.png",
      "portfolio/houm/houm_slide_18.png",
      "portfolio/houm/houm_slide_19.png",
      "portfolio/houm/houm_slide_20.png",
      "portfolio/houm/houm_slide_21.png",
      "portfolio/houm/houm_slide_22.png",
      "portfolio/houm/houm_slide_23.png",
      "portfolio/houm/houm_slide_24.png",
      "portfolio/houm/houm_slide_25.png",
      "portfolio/houm/houm_slide_26.png",
      "portfolio/houm/houm_slide_27.png",
      "portfolio/houm/houm_slide_28.png",
      "portfolio/houm/houm_slide_29.png",
      "portfolio/houm/houm_slide_30.png",
      "portfolio/houm/houm_slide_31.png",
      "portfolio/houm/houm_slide_32.png",
      "portfolio/houm/houm_slide_33.png",
      "portfolio/houm/houm_slide_34.png",
      "portfolio/houm/houm_slide_35.png",
      "portfolio/houm/houm_slide_36.png",
      "portfolio/houm/houm_slide_37.png",
      "portfolio/houm/houm_slide_38.png",
      "portfolio/houm/houm_slide_39.png",
      "portfolio/houm/houm_slide_40.png",
      "portfolio/houm/houm_slide_41.png",
      "portfolio/houm/houm_slide_42.png",
      "portfolio/houm/houm_slide_44.png",
      "portfolio/houm/houm_slide_45.png",
      "portfolio/houm/houm_slide_46.png",
      "portfolio/houm/houm_slide_47.png"
    ]
  },
  {
    "id": "wagh-bakri",
    "title": "Wagh Bakri Gourmet Tea Packaging",
    "client": "Wagh Bakri Tea Group",
    "category": "packaging",
    "categoryLabel": "Packaging",
    "scope": "Organic structure design, custom labels, packaging board layouts.",
    "description": "A luxury packaging design proposal for Wagh Bakri's Gourmet Specialty tea line. Drawing structural inspiration from traditional hand-woven tea-plucking baskets, the packaging incorporates organic wood grain textures, pastel color accents, and personalized plucker storytelling cards on each box.",
    "image": "portfolio/wagh-bakri/wagh-bakri_slide_1.png",
    "fileLink": "portfolio/wagh-bakri/wagh-bakri_slide_1.png",
    "fileType": "image",
    "fileLabel": "View Asset",
    "imagesList": [
      "portfolio/wagh-bakri/wagh-bakri_slide_1.png",
      "portfolio/wagh-bakri/wagh-bakri_slide_2.png",
      "portfolio/wagh-bakri/wagh-bakri_slide_3.png",
      "portfolio/wagh-bakri/wagh-bakri_slide_4.png",
      "portfolio/wagh-bakri/wagh-bakri_slide_5.png",
      "portfolio/wagh-bakri/wagh-bakri_slide_6.png",
      "portfolio/wagh-bakri/wagh-bakri_slide_7.png",
      "portfolio/wagh-bakri/wagh-bakri_slide_8.png",
      "portfolio/wagh-bakri/wagh-bakri_slide_9.png"
    ],
    "featuredImages": [
      "portfolio/wagh-bakri/wagh-bakri_slide_1.png",
      "portfolio/wagh-bakri/wagh-bakri_slide_2.png",
      "portfolio/wagh-bakri/wagh-bakri_slide_3.png",
      "portfolio/wagh-bakri/wagh-bakri_slide_4.png",
      "portfolio/wagh-bakri/wagh-bakri_slide_5.png",
      "portfolio/wagh-bakri/wagh-bakri_slide_6.png",
      "portfolio/wagh-bakri/wagh-bakri_slide_7.png",
      "portfolio/wagh-bakri/wagh-bakri_slide_8.png",
      "portfolio/wagh-bakri/wagh-bakri_slide_9.png"
    ],
    "archiveImages": []
  },
  {
    "id": "sebamed",
    "title": "Sebamed Skin Care Campaigns",
    "client": "Sebamed Germany",
    "category": "branding",
    "categoryLabel": "Brand Identity",
    "scope": "Creative marketing layouts, skin pH 5.5 banners, & promotional assets.",
    "description": "Visual campaign boards designed for Sebamed skincare. Focused heavily on high-contrast product staging, scientific pH 5.5 formulation advantages, and clinical cleansing branding lines tailored for digital and print distribution.",
    "image": "portfolio/sebamed/sebamed_slide_1.png",
    "fileLink": "portfolio/sebamed/sebamed_slide_1.png",
    "fileType": "image",
    "fileLabel": "View Asset",
    "imagesList": [
      "portfolio/sebamed/sebamed_slide_1.png",
      "portfolio/sebamed/sebamed_slide_2.png",
      "portfolio/sebamed/sebamed_slide_3.png",
      "portfolio/sebamed/sebamed_slide_4.png",
      "portfolio/sebamed/sebamed_slide_5.png",
      "portfolio/sebamed/sebamed_slide_6.png",
      "portfolio/sebamed/sebamed_slide_7.png",
      "portfolio/sebamed/sebamed_slide_8.png",
      "portfolio/sebamed/sebamed_slide_9.png",
      "portfolio/sebamed/sebamed_slide_10.png",
      "portfolio/sebamed/sebamed_slide_11.png",
      "portfolio/sebamed/sebamed_slide_12.png",
      "portfolio/sebamed/sebamed_slide_13.png",
      "portfolio/sebamed/sebamed_slide_14.png",
      "portfolio/sebamed/sebamed_slide_15.png",
      "portfolio/sebamed/sebamed_slide_16.png",
      "portfolio/sebamed/sebamed_slide_17.png",
      "portfolio/sebamed/sebamed_slide_18.png",
      "portfolio/sebamed/sebamed_slide_19.png",
      "portfolio/sebamed/sebamed_slide_20.png",
      "portfolio/sebamed/sebamed_slide_21.png",
      "portfolio/sebamed/sebamed_slide_22.png",
      "portfolio/sebamed/sebamed_slide_23.png",
      "portfolio/sebamed/sebamed_slide_24.png",
      "portfolio/sebamed/sebamed_slide_25.png",
      "portfolio/sebamed/sebamed_slide_27.png"
    ],
    "featuredImages": [
      "portfolio/sebamed/sebamed_slide_1.png",
      "portfolio/sebamed/sebamed_slide_2.png",
      "portfolio/sebamed/sebamed_slide_3.png",
      "portfolio/sebamed/sebamed_slide_4.png",
      "portfolio/sebamed/sebamed_slide_5.png",
      "portfolio/sebamed/sebamed_slide_6.png",
      "portfolio/sebamed/sebamed_slide_7.png",
      "portfolio/sebamed/sebamed_slide_8.png"
    ],
    "archiveImages": [
      "portfolio/sebamed/sebamed_slide_9.png",
      "portfolio/sebamed/sebamed_slide_10.png",
      "portfolio/sebamed/sebamed_slide_11.png",
      "portfolio/sebamed/sebamed_slide_12.png",
      "portfolio/sebamed/sebamed_slide_13.png",
      "portfolio/sebamed/sebamed_slide_14.png",
      "portfolio/sebamed/sebamed_slide_15.png",
      "portfolio/sebamed/sebamed_slide_16.png",
      "portfolio/sebamed/sebamed_slide_17.png",
      "portfolio/sebamed/sebamed_slide_18.png",
      "portfolio/sebamed/sebamed_slide_19.png",
      "portfolio/sebamed/sebamed_slide_20.png",
      "portfolio/sebamed/sebamed_slide_21.png",
      "portfolio/sebamed/sebamed_slide_22.png",
      "portfolio/sebamed/sebamed_slide_23.png",
      "portfolio/sebamed/sebamed_slide_24.png",
      "portfolio/sebamed/sebamed_slide_25.png",
      "portfolio/sebamed/sebamed_slide_27.png"
    ]
  },
  {
    "id": "storia",
    "title": "Storia Mango Shake Campaign",
    "client": "Storia Foods & Beverages",
    "category": "packaging",
    "categoryLabel": "Packaging",
    "scope": "Packaging Design Wraps, Key Visual Advertisements, Mockups & Campaign Identity.",
    "description": "This campaign details a complete graphic rebranding and packaging overhaul for Storia's Mango Shake line. Utilizing highly stylized, vibrant tropical mango illustrations alongside structured, modern block typography, the layouts establish a premium and refreshing consumer shelf presence. The creative direction centres around the emotional hook, 'Wish it never gets over,' emphasizing taste longevity and premium quality.",
    "image": "portfolio/storia/storia_slide_1.png",
    "fileLink": "portfolio/storia/storia_slide_1.png",
    "fileType": "image",
    "fileLabel": "View Asset",
    "imagesList": [
      "portfolio/storia/storia_slide_1.png",
      "portfolio/storia/storia_slide_2.png",
      "portfolio/storia/storia_slide_3.png",
      "portfolio/storia/storia_slide_4.png",
      "portfolio/storia/storia_slide_5.png",
      "portfolio/storia/storia_slide_6.png",
      "portfolio/storia/storia_slide_7.png",
      "portfolio/storia/storia_slide_8.png",
      "portfolio/storia/storia_slide_9.png",
      "portfolio/storia/storia_slide_10.png",
      "portfolio/storia/storia_slide_11.png"
    ],
    "featuredImages": [
      "portfolio/storia/storia_slide_1.png",
      "portfolio/storia/storia_slide_2.png",
      "portfolio/storia/storia_slide_3.png",
      "portfolio/storia/storia_slide_4.png",
      "portfolio/storia/storia_slide_5.png",
      "portfolio/storia/storia_slide_6.png",
      "portfolio/storia/storia_slide_7.png",
      "portfolio/storia/storia_slide_8.png"
    ],
    "archiveImages": [
      "portfolio/storia/storia_slide_9.png",
      "portfolio/storia/storia_slide_10.png",
      "portfolio/storia/storia_slide_11.png"
    ]
  },
  {
    "id": "scribble",
    "title": "Scribble Construction Branding",
    "client": "Scribble Construction",
    "category": "branding",
    "categoryLabel": "Brand Identity",
    "scope": "Logo design, business card concept, brand styling book, and intro animation.",
    "description": "Corporate brand book and logo concepts for Scribble Construction. It features high-end stationery designs with gold foil stamping on matte black backings, paired with custom motion graphics sequences visualizing corporate logo reveals.",
    "image": "portfolio/scribble/scribble_slide_1.png",
    "fileLink": "portfolio/scribble/scribble_slide_1.png",
    "fileType": "image",
    "fileLabel": "View Asset",
    "imagesList": [
      "portfolio/scribble/scribble_slide_1.png",
      "portfolio/scribble/scribble_slide_2.png",
      "portfolio/scribble/scribble_slide_3.png",
      "portfolio/scribble/scribble_slide_4.png",
      "portfolio/scribble/scribble_slide_5.png",
      "portfolio/scribble/scribble_slide_6.png",
      "portfolio/scribble/scribble_slide_7.png",
      "portfolio/scribble/scribble_slide_8.png",
      "portfolio/scribble/scribble_slide_9.png",
      "portfolio/scribble/scribble_slide_10.png",
      "portfolio/scribble/scribble_slide_11.png",
      "portfolio/scribble/scribble_slide_12.png"
    ],
    "featuredImages": [
      "portfolio/scribble/scribble_slide_1.png",
      "portfolio/scribble/scribble_slide_2.png",
      "portfolio/scribble/scribble_slide_3.png",
      "portfolio/scribble/scribble_slide_4.png",
      "portfolio/scribble/scribble_slide_5.png",
      "portfolio/scribble/scribble_slide_6.png",
      "portfolio/scribble/scribble_slide_7.png",
      "portfolio/scribble/scribble_slide_8.png"
    ],
    "archiveImages": [
      "portfolio/scribble/scribble_slide_9.png",
      "portfolio/scribble/scribble_slide_10.png",
      "portfolio/scribble/scribble_slide_11.png",
      "portfolio/scribble/scribble_slide_12.png"
    ]
  },
  {
    "id": "malabar",
    "title": "Malabar Product Launch Ads",
    "client": "Malabar Gold & Diamonds",
    "category": "branding",
    "categoryLabel": "Brand Identity",
    "scope": "Newspaper catalog ads, high-jewelry layout, print media design.",
    "description": "A print campaign consisting of 16x20 cm catalog advertisements for Malabar Gold & Diamonds. Layouts are optimized for regional newspaper and luxury magazine prints, displaying complex jewelry designs against clean, high-contrast backgrounds.",
    "image": "portfolio/malabar/image_1.jpg",
    "fileLink": "portfolio/malabar/image_1.jpg",
    "fileType": "image",
    "fileLabel": "View Asset",
    "imagesList": [
      "portfolio/malabar/image_1.jpg",
      "portfolio/malabar/image_2.jpg",
      "portfolio/malabar/image_3.jpg"
    ],
    "featuredImages": [
      "portfolio/malabar/image_1.jpg",
      "portfolio/malabar/image_2.jpg",
      "portfolio/malabar/image_3.jpg"
    ],
    "archiveImages": []
  },
  {
    "id": "kalam-kari",
    "title": "Kalam Kari Fashion Branding",
    "client": "Kalam Kari Ethnic Wear",
    "category": "branding",
    "categoryLabel": "Brand Identity",
    "scope": "Traditional pattern incorporation, box wraps, labels, and visual identity guides.",
    "description": "Brand book showcasing ethnic fashion design concepts based on the traditional Indian hand block print art style of Kalamkari. Incorporates organic maroons and indigo motifs on premium gold-embossed clothing tags and textile boxes.",
    "image": "portfolio/kalam-kari/kalam-kari_slide_1.png",
    "fileLink": "portfolio/kalam-kari/kalam-kari_slide_1.png",
    "fileType": "image",
    "fileLabel": "View Asset",
    "imagesList": [
      "portfolio/kalam-kari/kalam-kari_slide_1.png",
      "portfolio/kalam-kari/kalam-kari_slide_2.png",
      "portfolio/kalam-kari/kalam-kari_slide_3.png",
      "portfolio/kalam-kari/kalam-kari_slide_4.png",
      "portfolio/kalam-kari/kalam-kari_slide_5.png",
      "portfolio/kalam-kari/kalam-kari_slide_6.png",
      "portfolio/kalam-kari/kalam-kari_slide_7.png",
      "portfolio/kalam-kari/kalam-kari_slide_8.png",
      "portfolio/kalam-kari/kalam-kari_slide_9.png",
      "portfolio/kalam-kari/kalam-kari_slide_10.png"
    ],
    "featuredImages": [
      "portfolio/kalam-kari/kalam-kari_slide_1.png",
      "portfolio/kalam-kari/kalam-kari_slide_2.png",
      "portfolio/kalam-kari/kalam-kari_slide_3.png",
      "portfolio/kalam-kari/kalam-kari_slide_4.png",
      "portfolio/kalam-kari/kalam-kari_slide_5.png",
      "portfolio/kalam-kari/kalam-kari_slide_6.png",
      "portfolio/kalam-kari/kalam-kari_slide_7.png",
      "portfolio/kalam-kari/kalam-kari_slide_8.png"
    ],
    "archiveImages": [
      "portfolio/kalam-kari/kalam-kari_slide_9.png",
      "portfolio/kalam-kari/kalam-kari_slide_10.png"
    ]
  },
  {
    "id": "icef",
    "title": "ICEF Exhibition Banner Design",
    "client": "ICEF Global Education Fair",
    "category": "retail",
    "categoryLabel": "Retail & OOH",
    "scope": "Roll-up display banner, geometric layouts, print event branding.",
    "description": "A massive roll-up banner layout designed for ICEF education fair booths. The layout leverages gold and navy blue curves coupled with modern typography to deliver a highly readable, premium exhibition stand.",
    "image": "portfolio/icef/icef_slide_1.png",
    "fileLink": "portfolio/icef/icef_slide_1.png",
    "fileType": "image",
    "fileLabel": "View Asset",
    "imagesList": [
      "portfolio/icef/icef_slide_1.png"
    ],
    "featuredImages": [
      "portfolio/icef/icef_slide_1.png"
    ],
    "archiveImages": []
  },
  {
    "id": "radio-city",
    "title": "Radio City Campaign Creative",
    "client": "Radio City FM 91.1",
    "category": "branding",
    "categoryLabel": "Brand Identity",
    "scope": "Social media banners, print ads, and logo layouts.",
    "description": "A marketing layout designed for Radio City FM, one of India's biggest media networks. Displays bold graphic colors and brand positioning creatives aimed at increasing local listenership.",
    "image": "portfolio/radio-city/radio-city_image.jpg",
    "fileLink": "portfolio/radio-city/radio-city_image.jpg",
    "fileType": "image",
    "fileLabel": "View Asset",
    "imagesList": [
      "portfolio/radio-city/radio-city_image.jpg"
    ],
    "featuredImages": [
      "portfolio/radio-city/radio-city_image.jpg"
    ],
    "archiveImages": []
  },
  {
    "id": "ankahee",
    "title": "\"Ankahee Ansunee\" Video Project",
    "client": "Independent Short Film",
    "category": "media",
    "categoryLabel": "Video & Media",
    "scope": "Video editing, timeline cutting, transitions, and draft rendering.",
    "description": "An editing draft and post-production layout for a short film/video project titled 'Ankahee Ansunee' (translating to Unsaid, Unheard). Focuses on editing sequences, transitions, and audio-video timing overlays.",
    "image": "portfolio/assets/ankahee_layout.jpg",
    "fileLink": "portfolio/ankahee/ankahee_video.mp4",
    "fileType": "video",
    "fileLabel": "Play Video",
    "imagesList": [
      "portfolio/ankahee/ankahee_video.mp4"
    ],
    "featuredImages": [
      "portfolio/ankahee/ankahee_video.mp4"
    ],
    "archiveImages": []
  },
  {
    "id": "life-sand",
    "title": "\"Life\" Sand Animation",
    "client": "Creative Visual Project",
    "category": "media",
    "categoryLabel": "Video & Media",
    "scope": "Directing, physical sand-art recording, storyboards, and video assembly.",
    "description": "An artistic narrative short film featuring fluid, hand-drawn sand art animation sequences. Illustrates organic storylines transitions reflecting the cycle of 'Life'.",
    "image": "portfolio/life-sand/life-sand_thumb.png",
    "fileLink": "portfolio/life-sand/life-sand_video.mp4",
    "fileType": "video",
    "fileLabel": "Play Video",
    "imagesList": [
      "portfolio/life-sand/life-sand_video.mp4"
    ],
    "featuredImages": [
      "portfolio/life-sand/life-sand_video.mp4"
    ],
    "archiveImages": []
  },
  {
    "id": "ai-video",
    "title": "AI & Motion Video Generations",
    "client": "Visual Lab / Research",
    "category": "media",
    "categoryLabel": "Video & Media",
    "scope": "AI video rendering, seedance generation tests, and motion capture.",
    "description": "A series of experimental AI generations and video renders (such as seedance capture) designed for out-of-home video walls and responsive vertical billboards.",
    "image": "portfolio/assets/img_4637.jpg",
    "fileLink": "portfolio/ai-video/ai-video_video.mp4",
    "fileType": "video",
    "fileLabel": "Play Video",
    "imagesList": [
      "portfolio/ai-video/ai-video_video.mp4"
    ],
    "featuredImages": [
      "portfolio/ai-video/ai-video_video.mp4"
    ],
    "archiveImages": []
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = projectsData;
}
