const projectsData = [
  {
    "id": "canadiansim",
    "title": "CanadianSIM (Pre-Arrival SIM Cards)",
    "client": "CanadianSIM",
    "company": "Wireless DNA Inc.",
    "category": "branding",
    "categoryLabel": "Brand Identity",
    "scope": "Prepaid Website Redesign, UX & Web Design",
    "description": "CanadianSIM provides Canadian phone numbers and SIM plans to newcomers, international students, and travellers before they even land in the country. One website originally served both prepaid and postpaid users, and its lengthy checkout was quietly costing the business, prepaid buyers, mostly short-term tourist visitors and visa holders, were dropping off before completing their order. Tested a simplified Shopify Quick Checkout for prepaid users first, and once it proved out in real orders, led a full redesign of the prepaid site around that same logic. Conversion rate nearly doubled as a result.",
    "image": "portfolio/canadiansim/canadiansim_esim_ad.jpg",
    "fileLink": "portfolio/canadiansim/canadiansim_esim_ad.jpg",
    "fileType": "image",
    "fileLabel": "View Asset",
    "layout": "web-layout",
    "featuredImages": [
      "portfolio/canadiansim/canadiansim_esim_ad.jpg"
    ],
    "archiveImages": [],
    "performanceTable": [
      {
        "metric": "Conversion rate",
        "before": "3.96%",
        "after": "7.33%",
        "change": "+85%"
      },
      {
        "metric": "Bounce rate",
        "before": "50.96%",
        "after": "43.08%",
        "change": "-7.9 pts"
      },
      {
        "metric": "Average order value",
        "before": "$64.49",
        "after": "$70.74",
        "change": "+9.6%"
      },
      {
        "metric": "Revenue per day",
        "before": "$3,653",
        "after": "$4,763",
        "change": "+30.5%"
      },
      {
        "metric": "Orders per day",
        "before": "54",
        "after": "65",
        "change": "+20.9%"
      }
    ]
  },
  {
    "id": "rogers-fido-chatr",
    "title": "Rogers, Fido, Chatr",
    "client": "Rogers, Fido, Chatr",
    "company": "Wireless DNA Inc.",
    "category": "retail",
    "categoryLabel": "Retail & OOH",
    "scope": "Multi-Brand Creative, Retail & Airport",
    "description": "Maintain brand guidelines and design creative compliance across Rogers, Fido, and Chatr. Key executions include airport lounge and arrivals kiosk displays, mall billboards, spectacular layouts, store branding, and AI-assisted motion video content.",
    "image": "portfolio/rogers-fido-chatr/Image (1)_opt.jpg",
    "fileLink": "portfolio/rogers-fido-chatr/Image (1)_opt.jpg",
    "fileType": "image",
    "fileLabel": "View Asset",
    "layout": "vertical-sections",
    "sections": [
      {
        "title": "CONTEXT",
        "description": "Wireless DNA Inc. is an authorized dealer of Rogers, Fido, and Chatr, with 82+ locations across Canada, including airport locations at Toronto Pearson, Calgary, and Winnipeg.",
        "image": "portfolio/rogers-fido-chatr/Image (1)_opt.jpg"
      },
      {
        "title": "GUIDELINES",
        "description": "Maintained brand guidelines across Rogers, Fido, and Chatr, designing creative that stayed compliant across all three.",
        "image": "portfolio/rogers-fido-chatr/Image (2).jpg"
      },
      {
        "title": "AI VIDEO GENERATION",
        "description": "Produced ad-ready video content using Creatify AI, and animated static creative into motion pieces.",
        "video": "portfolio/rogers-fido-chatr/Video Gen-4488-0.mp4",
        "fileType": "video"
      },
      {
        "title": "OUTDOOR & DIGITAL",
        "description": "Designed creative for outdoor screens and spectaculars, social media campaigns, and Meta ads across all three brands.",
        "image": "portfolio/rogers-fido-chatr/Image (3).jpg"
      },
      {
        "title": "FIDO STORE POE",
        "description": "Designed store branding applied whenever a Fido location underwent rebranding or refresh.",
        "image": "portfolio/rogers-fido-chatr/Fido POE.jpeg"
      },
      {
        "title": "ROGERS STORE POE",
        "description": "Designed kiosk branding for airport locations, plus Rogers Preferred Program (RPP) flyers for airport employees.",
        "image": "portfolio/rogers-fido-chatr/Rogers POE.jpeg"
      },
      {
        "title": "TEAMS PRESENTATION",
        "description": "A motion mockup and creative reveal designed for corporate presentation and pitch guidelines.",
        "video": "portfolio/rogers-fido-chatr/MicrosoftTeams-video.mp4",
        "fileType": "video"
      },
      {
        "title": "CREATIVE CAMPAIGN CLIP 1",
        "description": "Social media motion creative outlining customized pre-arrival cellular activation programs.",
        "video": "portfolio/rogers-fido-chatr/WhatsApp Video 2026-07-14 at 4.44.00 PM.mp4",
        "fileType": "video"
      },
      {
        "title": "CREATIVE CAMPAIGN CLIP 2",
        "description": "Promotional mobile sequence highlight highlighting premium plans and localized rewards.",
        "video": "portfolio/rogers-fido-chatr/WhatsApp Video 2026-07-14 at 4.46.54 PM.mp4",
        "fileType": "video"
      },
      {
        "title": "CREATIVE CAMPAIGN CLIP 3",
        "description": "Branding story reveal outlining easy setup and sim card delivery benefits.",
        "video": "portfolio/rogers-fido-chatr/WhatsApp Video 2026-07-14 at 4.46.54 PM-2.mp4",
        "fileType": "video"
      }
    ]
  },
  {
    "id": "canadiansim-social",
    "title": "CanadianSIM",
    "client": "CanadianSIM",
    "company": "Wireless DNA Inc.",
    "category": "media",
    "categoryLabel": "Video & Media",
    "scope": "Social Media Management",
    "description": "Owned CanadianSIM's Instagram end to end, concept, copywriting, creative execution, and daily posting and scheduling, with full creative control over how the brand looked, sounded, and felt online. Set the tone for the account, establishing a consistent visual and voice identity that carried across every post. Concepts were developed independently, then written up into post captions and copy using Claude. Sourcing shifted depending on what each concept needed, stock photography for some creatives, AI-generated visuals using ChatGPT Pro for others. Static content led the page, but video ran alongside it: short-form customer testimonials shot and edited in CapCut, and static visuals brought to life using Seedance 2.0 to animate them into motion content. Grew the account from roughly 18,500 to 19,000 followers over the course of managing the page.",
    "image": "portfolio/canadiansim-social/01.png",
    "fileLink": "portfolio/canadiansim-social/01.png",
    "fileType": "image",
    "fileLabel": "View Asset",
    "layout": "phone-grid",
    "featuredImages": [
      "portfolio/canadiansim-social/01.png",
      "portfolio/canadiansim-social/21.png",
      "portfolio/canadiansim-social/23.png",
      "portfolio/canadiansim-social/31.png",
      "portfolio/canadiansim-social/02/01.png",
      "portfolio/canadiansim-social/02/02.png",
      "portfolio/canadiansim-social/03/01.png",
      "portfolio/canadiansim-social/03/02.png",
      "portfolio/canadiansim-social/04/01.png",
      "portfolio/canadiansim-social/04/02.png",
      "portfolio/canadiansim-social/05/01.png",
      "portfolio/canadiansim-social/05/02.png",
      "portfolio/canadiansim-social/06/01.png",
      "portfolio/canadiansim-social/06/02.png",
      "portfolio/canadiansim-social/07/01.png",
      "portfolio/canadiansim-social/07/02.png",
      "portfolio/canadiansim-social/08/01.png",
      "portfolio/canadiansim-social/08/02.png",
      "portfolio/canadiansim-social/09/01.png",
      "portfolio/canadiansim-social/09/02.png",
      "portfolio/canadiansim-social/10/01.png",
      "portfolio/canadiansim-social/10/02.png",
      "portfolio/canadiansim-social/11/01.png",
      "portfolio/canadiansim-social/11/02.png",
      "portfolio/canadiansim-social/12/01.png",
      "portfolio/canadiansim-social/12/02.png",
      "portfolio/canadiansim-social/13/01.png",
      "portfolio/canadiansim-social/13/02.png",
      "portfolio/canadiansim-social/14/01.png",
      "portfolio/canadiansim-social/14/02.png",
      "portfolio/canadiansim-social/15/01.png",
      "portfolio/canadiansim-social/15/02.png",
      "portfolio/canadiansim-social/15/03.png",
      "portfolio/canadiansim-social/15/04.png",
      "portfolio/canadiansim-social/16/01.png",
      "portfolio/canadiansim-social/16/02.png",
      "portfolio/canadiansim-social/17/01.png",
      "portfolio/canadiansim-social/17/02.png",
      "portfolio/canadiansim-social/18/01.png",
      "portfolio/canadiansim-social/18/02.png",
      "portfolio/canadiansim-social/19/01.png",
      "portfolio/canadiansim-social/19/02.png",
      "portfolio/canadiansim-social/19/03.png",
      "portfolio/canadiansim-social/20/01.png",
      "portfolio/canadiansim-social/20/02.png",
      "portfolio/canadiansim-social/22/01.png",
      "portfolio/canadiansim-social/22/02.png",
      "portfolio/canadiansim-social/23/01.png",
      "portfolio/canadiansim-social/23/02.png",
      "portfolio/canadiansim-social/24/01.png",
      "portfolio/canadiansim-social/24/02.png",
      "portfolio/canadiansim-social/25/01.png",
      "portfolio/canadiansim-social/25/02.png",
      "portfolio/canadiansim-social/26/01.png",
      "portfolio/canadiansim-social/26/02.png",
      "portfolio/canadiansim-social/27/01.png",
      "portfolio/canadiansim-social/27/02.png",
      "portfolio/canadiansim-social/28/01.png",
      "portfolio/canadiansim-social/28/02.png",
      "portfolio/canadiansim-social/29/01.png",
      "portfolio/canadiansim-social/29/02.png",
      "portfolio/canadiansim-social/30/01.png",
      "portfolio/canadiansim-social/30/02.png",
      "portfolio/canadiansim-social/30/03.png"
    ],
    "archiveImages": []
  },
  {
    "id": "airtel-black",
    "title": "Airtel Black Launch",
    "client": "Bharti Airtel (Airtel Black)",
    "category": "retail",
    "categoryLabel": "Retail & OOH",
    "scope": "Launch marketing, emailer (EDM) design, animation, & premium product presentation.",
    "description": "A digital launch marketing strategy for Bharti Airtel's premium bundled subscription plan, Airtel Black. Design files include high-end, responsive email layouts (EDMs) and motion GIFs targeted at presenting custom fiber, DTH, and mobile bundle services as a unified, luxury consumer solution.",
    "image": "portfolio/airtel-black/Untitled-3-01_opt.jpg",
    "fileLink": "portfolio/airtel-black/Untitled-3-01_opt.jpg",
    "fileType": "image",
    "fileLabel": "View Asset",
    "featuredImages": [
      "portfolio/airtel-black/Untitled-3-01_opt.jpg",
      "portfolio/airtel-black/Untitled-3-02.jpg",
      "portfolio/airtel-black/Untitled-3-03.jpg",
      "portfolio/airtel-black/WhatsApp Image 2021-07-19 at 11.08.13 AM.jpeg",
      "portfolio/airtel-black/Emailer /Platinum EDM 2-09.jpg",
      "portfolio/airtel-black/Emailer /Platinum-EDM-3_.gif"
    ],
    "archiveImages": []
  },
  {
    "id": "dailyhunt",
    "title": "Dailyhunt Identity Reimagined",
    "client": "Dailyhunt (News Aggregator App)",
    "category": "branding",
    "categoryLabel": "Brand Identity",
    "scope": "Logo design construct, brand guidelines, color theory, & brand books.",
    "description": "A complete reimagining of the visual identity for Dailyhunt, India's premier news aggregator. The branding strategy details a spiral construct merged into the letter 'd', conveying the ever-evolving nature of modern journalism, instant information flow, and growth.",
    "image": "portfolio/dailyhunt/slide_1.png",
    "fileLink": "portfolio/brand-identity/dailyhunt_brand identity.pdf",
    "fileType": "pdf",
    "fileLabel": "View Brand Book",
    "featuredImages": [
      "portfolio/dailyhunt/slide_1.png",
      "portfolio/dailyhunt/slide_2.png",
      "portfolio/dailyhunt/slide_3.png",
      "portfolio/dailyhunt/slide_4.png",
      "portfolio/dailyhunt/slide_5.png",
      "portfolio/dailyhunt/slide_6.png",
      "portfolio/dailyhunt/slide_7.png",
      "portfolio/dailyhunt/slide_8.png"
    ],
    "archiveImages": [
      "portfolio/dailyhunt/slide_9.png",
      "portfolio/dailyhunt/slide_10.png",
      "portfolio/dailyhunt/slide_11.png",
      "portfolio/dailyhunt/slide_12.png",
      "portfolio/dailyhunt/slide_13.png",
      "portfolio/dailyhunt/slide_14.png",
      "portfolio/dailyhunt/slide_15.png",
      "portfolio/dailyhunt/slide_16.png",
      "portfolio/dailyhunt/slide_17.png",
      "portfolio/dailyhunt/slide_18.png",
      "portfolio/dailyhunt/slide_19.png",
      "portfolio/dailyhunt/slide_20.png",
      "portfolio/dailyhunt/slide_21.png",
      "portfolio/dailyhunt/slide_22.png",
      "portfolio/dailyhunt/slide_23.png",
      "portfolio/dailyhunt/slide_24.png",
      "portfolio/dailyhunt/slide_25.png",
      "portfolio/dailyhunt/slide_26.png",
      "portfolio/dailyhunt/slide_27.png",
      "portfolio/dailyhunt/slide_28.png",
      "portfolio/dailyhunt/slide_29.png",
      "portfolio/dailyhunt/slide_30.png",
      "portfolio/dailyhunt/slide_31.png",
      "portfolio/dailyhunt/slide_32.png",
      "portfolio/dailyhunt/slide_33.png",
      "portfolio/dailyhunt/slide_34.png"
    ]
  },
  {
    "id": "houm",
    "title": "Houm Brand Book & Identity",
    "client": "Houm (houm.me)",
    "category": "branding",
    "categoryLabel": "Brand Identity",
    "scope": "Brand book creation, security concepts, galaxy-themed color palettes, & app design.",
    "description": "Branding project for Houm, a startup providing private internet spaces. The logo construct combines a cozy house silhouette (comfort) with a unique thumbprint (private security), rendered with planetary typography alignments and deep cosmic background textures.",
    "image": "portfolio/houm/slide_1_opt.jpg",
    "fileLink": "portfolio/brand-identity/final Houm_Book_1.pdf",
    "fileType": "pdf",
    "fileLabel": "View Brand Book",
    "featuredImages": [
      "portfolio/houm/slide_1_opt.jpg",
      "portfolio/houm/slide_2.png",
      "portfolio/houm/slide_3.png",
      "portfolio/houm/slide_4.png",
      "portfolio/houm/slide_5.png",
      "portfolio/houm/slide_6.png",
      "portfolio/houm/slide_7.png",
      "portfolio/houm/slide_8.png"
    ],
    "archiveImages": [
      "portfolio/houm/slide_9.png",
      "portfolio/houm/slide_10.png",
      "portfolio/houm/slide_11.png",
      "portfolio/houm/slide_12.png",
      "portfolio/houm/slide_13.png",
      "portfolio/houm/slide_14.png",
      "portfolio/houm/slide_15.png",
      "portfolio/houm/slide_16.png",
      "portfolio/houm/slide_17.png",
      "portfolio/houm/slide_18.png",
      "portfolio/houm/slide_19.png",
      "portfolio/houm/slide_20.png",
      "portfolio/houm/slide_21.png",
      "portfolio/houm/slide_22.png",
      "portfolio/houm/slide_23.png",
      "portfolio/houm/slide_24.png",
      "portfolio/houm/slide_25.png",
      "portfolio/houm/slide_26.png",
      "portfolio/houm/slide_27.png",
      "portfolio/houm/slide_28.png",
      "portfolio/houm/slide_29.png",
      "portfolio/houm/slide_30.png",
      "portfolio/houm/slide_31.png",
      "portfolio/houm/slide_32.png",
      "portfolio/houm/slide_33.png",
      "portfolio/houm/slide_34.png",
      "portfolio/houm/slide_35.png",
      "portfolio/houm/slide_36.png",
      "portfolio/houm/slide_37.png",
      "portfolio/houm/slide_38.png",
      "portfolio/houm/slide_39.png",
      "portfolio/houm/slide_40.png",
      "portfolio/houm/slide_41.png",
      "portfolio/houm/slide_42.png",
      "portfolio/houm/slide_43.png",
      "portfolio/houm/slide_44.png",
      "portfolio/houm/slide_45.png",
      "portfolio/houm/slide_46.png",
      "portfolio/houm/slide_47.png"
    ]
  },
  {
    "id": "wagh-bakri",
    "title": "Wagh Bakri Gourmet Tea Packaging",
    "client": "Wagh Bakri Tea Group",
    "category": "packaging",
    "categoryLabel": "Packaging",
    "scope": "Organic structure design, custom labels, packaging board layouts.",
    "description": "A luxury packaging design proposal for Wagh Bakri's Gourmet Specialty tea line. Drawing structural inspiration from traditional hand-woven tea-plucking baskets, the packaging incorporates organic wood grain textures, pastel color accents, and personalized plucker storytelling cards on each box.",
    "image": "portfolio/wagh-bakri/slide_1_opt.jpg",
    "fileLink": "portfolio/packaging/WaghBakri_packaging_Boards .pdf",
    "fileType": "pdf",
    "fileLabel": "View Packaging Boards",
    "featuredImages": [
      "portfolio/wagh-bakri/slide_1_opt.jpg",
      "portfolio/wagh-bakri/slide_2.png",
      "portfolio/wagh-bakri/slide_3.png",
      "portfolio/wagh-bakri/slide_4.png",
      "portfolio/wagh-bakri/slide_5.png",
      "portfolio/wagh-bakri/slide_6.png"
    ],
    "archiveImages": [
      "portfolio/wagh-bakri/slide_7.png",
      "portfolio/wagh-bakri/slide_8.png",
      "portfolio/wagh-bakri/slide_9.png"
    ]
  },
  {
    "id": "sebamed",
    "title": "Sebamed Skin Care Campaigns",
    "client": "Sebamed Germany",
    "category": "branding",
    "categoryLabel": "Brand Identity",
    "scope": "Creative marketing layouts, skin pH 5.5 banners, & promotional assets.",
    "description": "Visual campaign boards designed for Sebamed skincare. Focused heavily on high-contrast product staging, scientific pH 5.5 formulation advantages, and clinical cleansing branding lines tailored for digital and print distribution.",
    "image": "portfolio/sebamed/warmup_dumbbell.jpg",
    "fileLink": "portfolio/sebamed/Untitled(1).pdf",
    "fileType": "pdf",
    "fileLabel": "View Campaign Book",
    "featuredImages": [
      "portfolio/sebamed/warmup_dumbbell.jpg",
      "portfolio/sebamed/slide_2.png",
      "portfolio/sebamed/slide_3.png",
      "portfolio/sebamed/slide_4.png",
      "portfolio/sebamed/slide_5.png",
      "portfolio/sebamed/slide_6.png",
      "portfolio/sebamed/slide_7.png",
      "portfolio/sebamed/slide_8.png"
    ],
    "archiveImages": [
      "portfolio/sebamed/slide_9.png",
      "portfolio/sebamed/slide_10.png",
      "portfolio/sebamed/slide_11.png",
      "portfolio/sebamed/slide_12.png",
      "portfolio/sebamed/slide_13.png",
      "portfolio/sebamed/slide_14.png",
      "portfolio/sebamed/slide_15.png",
      "portfolio/sebamed/slide_16.png",
      "portfolio/sebamed/slide_17.png",
      "portfolio/sebamed/slide_18.png",
      "portfolio/sebamed/slide_19.png",
      "portfolio/sebamed/slide_20.png",
      "portfolio/sebamed/slide_21.png",
      "portfolio/sebamed/slide_22.png",
      "portfolio/sebamed/slide_23.png",
      "portfolio/sebamed/slide_24.png",
      "portfolio/sebamed/slide_25.png",
      "portfolio/sebamed/slide_26.png",
      "portfolio/sebamed/slide_27.png"
    ]
  },
  {
    "id": "storia",
    "title": "Storia Mango Shake Campaign",
    "client": "Storia Foods & Beverages",
    "category": "packaging",
    "categoryLabel": "Packaging",
    "scope": "Packaging Design Wraps, Key Visual Advertisements, Mockups & Campaign Identity.",
    "description": "This campaign details a complete graphic rebranding and packaging overhaul for Storia's Mango Shake line. Utilizing highly stylized, vibrant tropical mango illustrations alongside structured, modern block typography, the layouts establish a premium and refreshing consumer shelf presence. The creative direction centres around the emotional hook, 'Wish it never gets over,' emphasizing taste longevity and premium quality.",
    "image": "portfolio/storia/storia_mango_shake.jpg",
    "fileLink": "portfolio/storia/Untitled-2.pdf",
    "fileType": "pdf",
    "fileLabel": "View Campaign Deck",
    "featuredImages": [
      "portfolio/storia/storia_mango_shake.jpg",
      "portfolio/storia/slide_2.png",
      "portfolio/storia/slide_3.png",
      "portfolio/storia/slide_4.png",
      "portfolio/storia/slide_5.png",
      "portfolio/storia/slide_6.png"
    ],
    "archiveImages": [
      "portfolio/storia/slide_7.png",
      "portfolio/storia/slide_8.png",
      "portfolio/storia/slide_9.png",
      "portfolio/storia/slide_10.png",
      "portfolio/storia/slide_11.png"
    ]
  },
  {
    "id": "scribble",
    "title": "Scribble Construction Branding",
    "client": "Scribble Construction",
    "category": "branding",
    "categoryLabel": "Brand Identity",
    "scope": "Logo design, business card concept, brand styling book, and intro animation.",
    "description": "Corporate brand book and logo concepts for Scribble Construction. It features high-end stationery designs with gold foil stamping on matte black backings, paired with custom motion graphics sequences visualizing corporate logo reveals.",
    "image": "portfolio/scribble/slide_1_opt.jpg",
    "fileLink": "portfolio/brand-identity/Scribble Construction /Sequence 03.mp4",
    "fileType": "video",
    "pdfLink": "portfolio/brand-identity/Scribble Construction /Untitled.pdf",
    "fileLabel": "Play Video Reveal",
    "featuredImages": [
      "portfolio/scribble/slide_1_opt.jpg",
      "portfolio/scribble/slide_2.png",
      "portfolio/scribble/slide_3.png",
      "portfolio/scribble/slide_4.png",
      "portfolio/scribble/slide_5.png",
      "portfolio/scribble/slide_6.png"
    ],
    "archiveImages": [
      "portfolio/scribble/slide_7.png",
      "portfolio/scribble/slide_8.png",
      "portfolio/scribble/slide_9.png",
      "portfolio/scribble/slide_10.png",
      "portfolio/scribble/slide_11.png",
      "portfolio/scribble/slide_12.png"
    ]
  },
  {
    "id": "malabar",
    "title": "Malabar Product Launch Ads",
    "client": "Malabar Gold & Diamonds",
    "category": "branding",
    "categoryLabel": "Brand Identity",
    "scope": "Newspaper catalog ads, high-jewelry layout, print media design.",
    "description": "A print campaign consisting of 16x20 cm catalog advertisements for Malabar Gold & Diamonds. Layouts are optimized for regional newspaper and luxury magazine prints, displaying complex jewelry designs against clean, high-contrast backgrounds.",
    "image": "portfolio/malabar/malabar_bloom_ad.jpg",
    "fileLink": "portfolio/malabar/malabar_bloom_ad.jpg",
    "fileType": "image",
    "fileLabel": "View Asset",
    "featuredImages": [
      "portfolio/malabar/malabar_bloom_ad.jpg",
      "portfolio/malabar/16x20cms-Ads-03.jpg",
      "portfolio/malabar/16x20cms-Ads-04.jpg"
    ],
    "archiveImages": []
  },
  {
    "id": "kalam-kari",
    "title": "Kalam Kari Fashion Branding",
    "client": "Kalam Kari Ethnic Wear",
    "category": "branding",
    "categoryLabel": "Brand Identity",
    "scope": "Traditional pattern incorporation, box wraps, labels, and visual identity guides.",
    "description": "Brand book showcasing ethnic fashion design concepts based on the traditional Indian hand block print art style of Kalamkari. Incorporates organic maroons and indigo motifs on premium gold-embossed clothing tags and textile boxes.",
    "image": "portfolio/kalam-kari/kalamkari_cardboard_logo.jpg",
    "fileLink": "portfolio/brand-identity/Kalam Kari .pdf",
    "fileType": "pdf",
    "fileLabel": "View Brand Book",
    "featuredImages": [
      "portfolio/kalam-kari/kalamkari_cardboard_logo.jpg",
      "portfolio/kalam-kari/slide_2.png",
      "portfolio/kalam-kari/slide_3.png",
      "portfolio/kalam-kari/slide_4.png",
      "portfolio/kalam-kari/slide_5.png",
      "portfolio/kalam-kari/slide_6.png"
    ],
    "archiveImages": [
      "portfolio/kalam-kari/slide_7.png",
      "portfolio/kalam-kari/slide_8.png",
      "portfolio/kalam-kari/slide_9.png",
      "portfolio/kalam-kari/slide_10.png"
    ]
  },
  {
    "id": "radio-city",
    "title": "Radio City Campaign Creative",
    "client": "Radio City FM 91.1",
    "category": "branding",
    "categoryLabel": "Brand Identity",
    "scope": "Social media banners, print ads, and logo layouts.",
    "description": "A marketing layout designed for Radio City FM, one of India's biggest media networks. Displays bold graphic colors and brand positioning creatives aimed at increasing local listenership.",
    "image": "portfolio/radio-city/radiocity_rofl_ad.jpg",
    "fileLink": "portfolio/radio-city/radiocity_rofl_ad.jpg",
    "fileType": "image",
    "fileLabel": "View Asset",
    "featuredImages": [
      "portfolio/radio-city/radiocity_rofl_ad.jpg"
    ],
    "archiveImages": []
  },
  {
    "id": "ankahee",
    "title": "\"Ankahee Ansunee\" Video Project",
    "client": "Independent Short Film",
    "category": "media",
    "categoryLabel": "Video & Media",
    "scope": "Video editing, timeline cutting, transitions, and draft rendering.",
    "description": "An editing draft and post-production layout for a short film/video project titled 'Ankahee Ansunee' (translating to Unsaid, Unheard). Focuses on editing sequences, transitions, and audio-video timing overlays.",
    "image": "portfolio/assets/ankahee_layout_opt.jpg",
    "fileLink": "portfolio/ankahee/Ankahee Ansunee_1stDraft.mp4",
    "fileType": "video",
    "fileLabel": "Play Video",
    "featuredImages": [
      "portfolio/ankahee/Ankahee Ansunee_1stDraft.mp4"
    ],
    "archiveImages": []
  },
  {
    "id": "life-sand",
    "title": "\"Life\" Sand Animation",
    "client": "Creative Visual Project",
    "category": "media",
    "categoryLabel": "Video & Media",
    "scope": "Directing, physical sand-art recording, storyboards, and video assembly.",
    "description": "An artistic narrative short film featuring fluid, hand-drawn sand art animation sequences. Illustrates organic storylines transitions reflecting the cycle of 'Life'.",
    "image": "portfolio/life-sand/life-sand_thumb_opt.jpg",
    "fileLink": "portfolio/life-sand/Life_Sand Animation.mp4",
    "fileType": "video",
    "fileLabel": "Play Video",
    "featuredImages": [
      "portfolio/life-sand/Life_Sand Animation.mp4"
    ],
    "archiveImages": []
  },
  {
    "id": "apple",
    "title": "India iStore, Apple Authorised Reseller",
    "client": "India iStore, Apple Authorised Reseller",
    "category": "media",
    "categoryLabel": "Video & Media",
    "scope": "Apple Watch for Mother's Day Campaign",
    "description": "Led copywriting and art direction for the Apple Watch Mother's Day social campaign, positioning the watch around a single insight: mothers spend a lifetime looking after everyone else's health. Each post paired a health feature, ECG, blood oxygen, activity tracking, with a line that turned the gift into a role reversal, \"she took care of your heartbreaks, it's time you take care of her heart rate.\"",
    "image": "portfolio/apple/Mother_s Day-06.jpg",
    "fileLink": "portfolio/apple/Mother_s Day-06.jpg",
    "fileType": "image",
    "fileLabel": "View Asset",
    "layout": "phone-grid",
    "featuredImages": [
      "portfolio/apple/Mother_s Day-06.jpg",
      "portfolio/apple/Mother_s Day-07.jpg",
      "portfolio/apple/Mother_s Day-08.jpg",
      "portfolio/apple/Mother_s Day-09.jpg",
      "portfolio/apple/Mother_s Day-10.jpg",
      "portfolio/apple/Mother_s Day-11.jpg",
      "portfolio/apple/Mother_s Day-12.jpg",
      "portfolio/apple/Mother_s Day-13.jpg",
      "portfolio/apple/Mother_s Day-14.jpg",
      "portfolio/apple/Mother_s Day-15.jpg",
      "portfolio/apple/Mother_s Day_route 1-17.jpg",
      "portfolio/apple/Mother_s Day_route 1-18.jpg",
      "portfolio/apple/Mother_s Day_route 1-19.jpg",
      "portfolio/apple/Mother_s Day_route 1-20.jpg"
    ],
    "archiveImages": []
  },
  {
    "id": "taj",
    "title": "The Taj Mahal Hotel",
    "client": "The Taj Mahal Hotel, New Delhi",
    "agency": "Leo Burnett",
    "category": "branding",
    "categoryLabel": "Brand Identity",
    "scope": "One Mansingh Road, Print Ad",
    "description": "One Mansingh Road has quietly hosted Delhi's most private moments, budget meetings, first dates, a generation's first taste of authentic Sichuan food, long before the hotel needed to say so. Art directed a print ad for the Taj Mahal Hotel's relaunch that leaned entirely on that history rather than the renovation itself. The message wasn't \u201cwe've redecorated,\u201d it was \u201cthis address has always meant something, and now it's ready for your story too.\u201d The new decor and refreshed spaces were positioned as an invitation to add to that history, not a reason to visit for the first time.",
    "image": "portfolio/taj/taj_mansingh_ad.jpg",
    "fileLink": "portfolio/taj/taj_mansingh_ad.jpg",
    "fileType": "image",
    "fileLabel": "View Asset",
    "featuredImages": [
      "portfolio/taj/taj_mansingh_ad.jpg",
      "portfolio/taj/taj-1-02.jpg"
    ],
    "archiveImages": []
  }
];

